### ISSUE TITLE
CSV Sample file

### ISSUE THREAD

**Issue by sechix** [2beDigital/solidus_import_products#1]
Hi, thanks for your gem. Could you provide a csv file example, I am a little confusing about fields to fill

**Comment by SergiCarrasco** [comment]
Hi @sechix,
We are still in the process of implementing Solidus, so we still have this gem for Solidus in "beta" and it isn't yet functional.
Thanks.

**Comment by sechix** [comment]
hello is already finish?

**Comment by NoelDiazMesa** [comment]
Yes @sechix , it is finished... you can try.
