### ISSUE TITLE
undefined method `with_translations' for #<Class:0x007f89bc43f3d0> Did you mean? with_variant_sku_cont

### ISSUE THREAD

**Issue by oscar6654** [2beDigital/solidus_import_products#7]
i installed delayed_job with active record gem and migrated all the needed files and doing rake jobs:work. I am getting 

`undefined method `with_translations' for #<Class:0x007f89bc43f3d0> Did you mean? with_variant_sku_cont`

error when uploading a csv, i used the sample csv provided from the spec test

**Comment by NoelDiazMesa** [comment]
Which version of solidus?? In solidus we use sucker punch, no delayed_jobs
